import { defineConfig } from "@pandacss/dev";

/**
 * Panda CSS configuration for ampersand-frontend-web.
 *
 * Styling stack: Ark UI + Zag.js (logic) · Panda CSS (styling) · tokens below (theming).
 * Dark mode is intentionally NOT used — tokens are single-value (light only).
 *
 * Tokens were migrated verbatim from the previous Tailwind v4 `main.css` (`:root` block).
 * Paired tokens (e.g. `primary` / `primary-foreground`) use Panda's `DEFAULT` + nested-key
 * convention so they can be addressed as `primary` and `primary.foreground` in recipes.
 */
export default defineConfig({
  // CSS reset (replaces Tailwind's preflight)
  preflight: true,

  // Scan Vue + TS sources for style declarations
  include: ["./src/**/*.{js,jsx,ts,tsx,vue}"],
  exclude: [],

  // Output directory (regenerated by `panda codegen`; gitignored)
  outdir: "styled-system",

  // Vue uses the css/cva/recipe APIs directly (no JSX `styled` factory needed),
  // so we intentionally do NOT set `jsxFramework`.

  // Map Ark UI's data attributes to Panda conditions so recipes can use
  // `_open`, `_closed`, `_expanded`, etc.
  conditions: {
    extend: {
      open: '&[data-state="open"]',
      closed: '&[data-state="closed"]',
      expanded: "&[data-expanded]",
    },
  },

  theme: {
    extend: {
      tokens: {
        fonts: {
          display: { value: "'Aboreto', sans-serif" },
          ui: {
            value: "'Cantarell', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
          },
          body: {
            value: "'IBM Plex Sans', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
          },
          mono: {
            value: "'IBM Plex Mono', ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
          },
        },
        radii: {
          sm: { value: "calc(0.625rem - 4px)" },
          md: { value: "calc(0.625rem - 2px)" },
          lg: { value: "0.625rem" },
          xl: { value: "calc(0.625rem + 4px)" },
        },
      },
      semanticTokens: {
        colors: {
          background: { value: "oklch(1 0 0)" },
          foreground: { value: "oklch(0.145 0 0)" },

          card: {
            DEFAULT: { value: "oklch(1 0 0)" },
            foreground: { value: "oklch(0.145 0 0)" },
          },
          popover: {
            DEFAULT: { value: "oklch(1 0 0)" },
            foreground: { value: "oklch(0.145 0 0)" },
          },
          primary: {
            DEFAULT: { value: "oklch(0.205 0 0)" },
            foreground: { value: "oklch(0.985 0 0)" },
          },
          secondary: {
            DEFAULT: { value: "oklch(0.97 0 0)" },
            foreground: { value: "oklch(0.205 0 0)" },
          },
          muted: {
            DEFAULT: { value: "oklch(0.97 0 0)" },
            foreground: { value: "oklch(0.556 0 0)" },
          },
          accent: {
            DEFAULT: { value: "oklch(0.97 0 0)" },
            foreground: { value: "oklch(0.205 0 0)" },
          },

          destructive: { value: "oklch(0.577 0.245 27.325)" },
          border: { value: "oklch(0.922 0 0)" },
          input: { value: "oklch(0.922 0 0)" },
          ring: { value: "oklch(0.708 0 0)" },

          chart: {
            1: { value: "oklch(0.87 0 0)" },
            2: { value: "oklch(0.556 0 0)" },
            3: { value: "oklch(0.439 0 0)" },
            4: { value: "oklch(0.371 0 0)" },
            5: { value: "oklch(0.269 0 0)" },
          },

          sidebar: {
            DEFAULT: { value: "oklch(0.985 0 0)" },
            foreground: { value: "oklch(0.145 0 0)" },
            primary: {
              DEFAULT: { value: "oklch(0.205 0 0)" },
              foreground: { value: "oklch(0.985 0 0)" },
            },
            accent: {
              DEFAULT: { value: "oklch(0.97 0 0)" },
              foreground: { value: "oklch(0.205 0 0)" },
            },
            border: { value: "oklch(0.922 0 0)" },
            ring: { value: "oklch(0.708 0 0)" },
          },
        },
      },
    },
  },
});
